### ISSUE TITLE
Interstate meeting

### ISSUE THREAD

**Issue by kushsingh28** [ayazhafiz/meetHere#3]
### Issue
Interstate/intercity/international meeting locations are not working.

### Expected behavior
Locations in a non-habitable place (s.a. water) are pulled to the nearest land location

### Actual behavior (of issue)
The app pulls it in the middle of no where.

### Steps to reproduce (issue)
Meet with a friend across state/ national lines and over a sizable body of water so that the calculated equidistant point is in water.

### Proposed solutions, including designs, code, other relevant information / files
We need to have the application extend the "radius" and search for the highest rated places when the equidistant meeting location is in the "middle of nowhere"

**Comment by ayazhafiz** [comment]
I wrote a very long, detailed comment about this issue... and then shut down my computer. So, too long, didn't want to write:

### To do this, we need to exhaust our server resources, or otherwise place strain on the client's user experience.  

Essentially, what we will have to do is check the equidistant location's pixel color (source [1](http://stackoverflow.com/a/9644812/6312217), [2](http://stackoverflow.com/a/14460098/6312217), [3](https://tech.bellycard.com/blog/where-d-the-water-go-google-maps-water-pixel-detection-with-canvas/), which in many cases is CPU demanding and cumbersome.  
Fortunately, that is relatively easy; the difficult part is finding the nearest coastline location. On a high level, I understand how this works: you draw coastline polygons and save it server side until you need to check for which polygon vertex is nearest the location. In practice, I have no idea where to begin; there is very little literature on the matter (only found [one article](http://gis.stackexchange.com/questions/22023/finding-the-nearest-landmass-to-a-point-in-the-ocean-via-api)), but there is a [nice webapp](http://www.maprisk.com) that has completed this objective. Unfortunately, its protocol is http (not accessible by our secure app) and its API is private 😕. 

Ultimately, then, we must consider the following:
> Is it worth dedicating the time and resources needed to solve this problem in our current application state?

We must ponder the use cases and scenarios in which people will be searching for meeting locations across state and national lines - how common will that be, and if it occurs, how often will the bug appear? Personally, I do not feel that a person in Santa Monica will often be searching for a equidistant location with someone from Belarus - if these are businesses, the consultant almost always flies out directly to the client. Yes, it would be a nice bug to fix, but I'm not sure it's worth the resources given the negligible **practical** solution it invokes (though the UI would look better). That is why I have given it the label low priority, and if no other input is given within two days, this issue will be locked to outside respondents.

**Comment by kushsingh28** [comment]
this is indeed a very practical issue to focus on. One of our value propositions is how effective and accurate our software is. Refining things like this is primary and should take precedence over anything else. At the end of the day, our calculations and accuracy is going to bring customers. We must establish ourselves as THE app to meet. Therefore, I think this should take precedence over any current issues that we have right now. ( Also, i get nailed with this question  a lot, so its apparent that people care)

**Comment by ayazhafiz** [comment]
Zipper and I have put it on the back burner for now. Of course, it would be a nice problem to solve, but we have more pressing issues and do not have the time to delegate 15 days towards solving this issue. Zipper and I will revisit implementation of it after all our objectives have passed critical state.

**Comment by ayazhafiz** [comment]
Requirements:
- Database w/ coastlines
- >2 GB ram (upgrade Heroku)
- client-side optimization (for CPU usage) or polygon storage (memory)
